blog/config/routes.rb
Rails.application.routes.draw do
  get '/signup' => 'users#new'
  resources :users
  resources :articles
  get '/login' => 'session#new', as: :login
  post 'login' => 'session#create'
  delete '/logout' => 'session#destroy'
  get '/your_posts' => 'articles#user_articles', as: :your_posts

  root 'session#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user

  validates :body, presence: true
end

blog/app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :articles, dependent: :destroy

	validates :name, presence: true
	validates :email, presence: true
	validates :password, presence: true
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  add_flash_types :danger, :success, :warning
	def current_user
	  @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
	end

	def require_user
  	unless current_user
  		redirect_to login_path, notice: 'Faça login'
  	end
	end
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_user, only: [:index, :show, :create, :edit, :update, :destroy, :new, :user_articles]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @article = Article.new
  end

  def user_articles
    @articles = Article.where(user_id: session[:user_id])
    @article = Article.new
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
  end

  # GET /articles/new
  #def new
    #@article = Article.new
  #end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_back fallback_location: request.referrer, success: "Post criado!"
    else
      redirect_back fallback_location: request.referrer, danger: "O post deve conter algo!"
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    if @current_user.id == @article.user_id
      @article.destroy
      redirect_to articles_path, warning: 'Post deletado.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:body).merge(:user_name => @current_user.name)
    end
end

blog/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  	if current_user
  		redirect_to articles_path
  	end
	end

	def create
	  @user = User.find_by_email(params[:session][:email])
	  if @user && @user.authenticate(params[:session][:password])
	    session[:user_id] = @user.id
	    redirect_to articles_path
	  else
	    redirect_to login_path, notice: 'Nenhum usuário cadastrado'
	  end
	end

	def destroy
  	session[:user_id] = nil
  	redirect_to login_path
	end
end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /users
  # GET /users.json
  def index
    if !current_user
      @users = User.all
    else
      redirect_to articles_path
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show

  end

  def edit

  end

  # GET /users/new
  def new
    if !current_user
      @user = User.new
      render layout: "signup"
    else
      redirect_to articles_path
    end
  end


  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to login_path, notice: 'Perfil cadastrado com sucesso'
    else
      render :new, notice: 'Não foi possível cadastra-lo, preencha todos os campos'
    end

  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/session_helper.rb
module SessionHelper
end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <div class='new-post'>
    <%form.label :body %>
    <%= form.text_area :body, class: 'new-post-body' %>
    <%= form.submit 'POST', class: 'new-post-btn btn btn-success'  %>
  </div>
<% end %>

blog/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

blog/app/views/articles/index.html.erb
<h1 align='center'>Posts</h1>
<%flash.each do |name, msg| %>
  <div class='alert alert-<%=name%>' id="post-msg"><%=msg%></div>
<%end%>
<%= render 'form', article: @article %>
<div class='container posts'>
  <div class='post'>
    <% @articles.each do |article| %>
      <strong>
        <div id='user'>
          <%= article.user_name%>
        </div>
        <span id='post-date'>postado em: <%= article.created_at.strftime('%d/%b')%></span>
      </strong>
      <div id='content'>
        <p id='body'><%= article.body %></p>
      </div>
      <%if @current_user.id == article.user_id %>
        <div class='post-btn'>
          <%= link_to 'Show', article_path(article), class: 'btn btn-info' %>
          <%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-dark'%>
        </div>
      <%else%>
        <div class='post-btn-show'>
          <%= link_to 'Show', article_path(article), class: 'btn btn-info' %>
        </div>
      <%end%>
    <% end %>
  </div>
</diav>

blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

blog/app/views/articles/show.html.erb
<div class='container posts'>
	<div class='post'>
    <strong>
		  <div id='user'>
        <%= @article.user_name%>
      </div>
      <span id='post-date'>postado em: <%= @article.created_at.strftime('%d/%b')%></span>
    </strong>
    <div id='content'>
      <p id='body'><%= @article.body %></p>
    </div>
		<%if @current_user.id == @article.user_id %>
			<%= link_to 'Destroy', article_path(@article), method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-dark post'%>
		<%end%>
	</div>
</div>

blog/app/views/articles/user_articles.html.erb
<h1 align="center"> Seus Posts </h1>
<%flash.each do |name, msg| %>
  <div class='alert alert-<%=name%>' id="post-msg"><%=msg%></div>
<%end%>
<%= render 'form', article: @article %>

<% if @articles == nil%>
	Você não possui nenhum post
<%else%>
	<div class='container posts'>
		<% @articles.each do |article| %>
		 <div class='post'>
		 	<div id='post-date-user'>
		 		postado em: <%= article.created_at.strftime('%d/%b')%>
		 	</div>
		 	<div id='content'>
	        	<p id='body'><%= article.body %></p>
	        </div>
	        <div class='post-btn'>
        		<%= link_to 'Show', article_path(article), class: 'btn btn-info' %>
        		<%if @current_user.id == article.user_id %>
          		<%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-dark' %>
          		<%end%>
      			</div>

		<%end%>
	</div>
<%end%>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
    <h1 align='center' id='tZombies'>TWITTER FOR ZOMBIES</h1>
    <% if current_user %>
      <ul style="list-style-type: none;">
        <li id='welcome' class='alert alert-success'>Bem vindo de volta, <%= current_user.name %>!</li>
      </ul>
      <div class='menu'>
        <%= link_to "Seus Posts", '/your_posts', class: 'btn btn-info'%>
        <%= link_to "Todos Posts", articles_path, class: 'btn btn-warning'%>
        <%= link_to "Log out", logout_path, method: "delete", class: 'btn btn-danger'%>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

blog/app/views/layouts/signup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Signup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

blog/app/views/session/new.html.erb
<p id="notice" align="center"><%= notice%></p>
<div class='container login'>
	<h1 id='login-label'><strong>Login</strong></h1>
	<%= form_for(:session, url: login_path) do |f| %>

		 <%= f.email_field :email, :placeholder => "Email", class: 'form-field' %>
	  	<br>
	  	 <%= f.password_field :password, :placeholder => "Senha", class: 'form-field' %>
	  	<br>
	  	<%= f.submit "Sign in", class: "btn-login" %>
	  	<a><%= link_to "Signup", '/signup', class: 'btn btn-info signup' %></a>
	<% end %>
</div>

blog/app/views/users/_form.html.erb
<div class='container login'>
  <h1 id='new-label'><strong>Nova Conta</strong></h1>
  <%= form_with model: user, local: true do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> Não foi possível criar este usuário:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= form.text_field :name, :placeholder => "Name", class: 'form-field'%>
    <%= form.email_field :email, :placeholder => "Email", class: 'form-field' %>
    <%= form.password_field :password, :placeholder => "Password", class: 'form-field'%>
    <%= form.submit 'Sign Up', class: 'btn btn-info signup'%>
  <% end %>
    <a><%= link_to 'Back', login_path, class: 'btn btn-danger back'%></a>
</div>

blog/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

blog/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

blog/app/views/users/new.html.erb
<%= render 'form', user: @user %>

blog/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>